### ISSUE TITLE
Documention for setup procedure

### ISSUE THREAD

**Issue by simonrepp** [apertus-open-source-cinema/elmyra#1]
Working on it!

**Comment by simonrepp** [comment]
There should be enough documentation to get Elmyra up and running now (although I will continue improving it in the near future), I'm leaving this open for the moment, feel free to let me know if anything is missing, wrong, or could be substantially better!

**Comment by thesourcerer8** [comment]
I would suggest (and will provide a pull-request) to rewrite the installation instructions into a more linear form, I had to jump back and forth between the various segments, looking whether I missed something.
Another thing I figured out later is that we should add minimum version numbers required.
What I found out so far: 
Blender 2.69 is most likely too old, some of the library files were made with a newer version
ffmpeg 6:0.8.10-0 is too old, it does not understand a commandline option used by elmyra

**Comment by andistern** [comment]
suggest to add detailed setup instructions for Mac OS X - setting an alias ( `alias blender='path to blender executable'` ) or linking blender ( `ln -s /path/to/blender /usr/local/bin` ) did not work for me, but extending the path ( `export PATH=$PATH:/path/to` ) did. 

Are the Version numbers that strict ( `==` ) or could this be also a `>=` ? as requirements.txt states

```
certifi=2015.9.6.2
flask==0.10.1
natsort==4.0.4
pillow==2.7.0
python-slugify==1.1.3
requests==2.4.3
```

as `blender-2.76-5f0cf67-OSX-10.6-x86_64` comes with `requests==2.5.0`

**Comment by simonrepp** [comment]
@thesourcerer8 I didn't want to scare off people with a 2 page linear instruction manual :), and some people will always be at a disadvantage either way (overview vs. details - everyone has a different approach to learning/doing), but feel free to propose changes where you deem them necessary! 

Minimum version requirements - definitely! I've done some planning towards tying elmya releases to specific blender releases, which solves the minimum requirements question for blender (but has a different reasoning originally). For ffmpeg I think this is related to a gif encoding feature that's only available in later ffmpeg versions, i planned to make an intelligent switch in the code which uses either the old or the new encoding path, but i might have skipped this or forgot it, either way this will need a minimum requirement soon. Ideally I want to bundle ffmpeg with releases though, haven't had time to think it through yet.

@andistern I am 99% sure that blender (including the tweaked python environment) will be bundled with elmyra releases starting as soon as i figure out the remaining issues for it, so the documentation for this will be unnecessary, that said I don't really want to invest time into this, and I don't have it anyway. So much other stuff to solve and figure out. :)

**Comment by simonrepp** [comment]
I'm closing this now - I want to make as much of this existing documentation unnecessary  by simplifying the setup itself, until then work on documentation is possibly badly invested time because it might get outdated meanwhile.
