### ISSUE TITLE
Investigate Media Length as an implicit choice through other options

### ISSUE THREAD

**Issue by simonrepp** [apertus-open-source-cinema/elmyra#19]
Possible implementation strategy:
- `Still` and `Animation` media types both converge into a single `Rendered` media type, adaptively covering either the first or the latter based on choices in the wizard.
- The explicit media length wizard page is dropped entirely.
- Media length is dictated by a "How fast should the turntable camera spin" option (with a live preview of the turntable so that it is more tangible) - this might also display in how long an animation this results.
- Media length is dictated by a "How fast should the cross-section cut progress through the mesh" option (with live preview, again, also possibly displaying resulting length)
- A generic warning is displayed when certain implicit options make the animation length dangerously long (in terms of predicted render time)
- Possibly there's a generic info item that shows in real time whether the result will be an image or an animation based on the current choices?

Questions:
- Which modules in the code are responsible for setting the media length then? Does the wizard automatically derive it at the end of alls steps?
- How to handle conflicting implicit options? For instance a fast turntable with a slow cross-section animation, or vice versa? Is the turntable handled as something "loopable" or as an animation with start and end for single play usage?

**Comment by thesourcerer8** [comment]
If you have already rendered a slow turntable animation, then you could also easily generate a fast turntable animation by skipping every second rendered frame, and offer both versions? Another idea: You could "bake" it for a slow animation, then first start rending only every 4th frame and generate fast version, then the 2nd frames in between for the normal version and when you are finished you can calculate the missing frames and generate the slow version. So the fast version will be completed first, and the slower versions will be available later on. Just an idea, I am not sure, whether that will be needed in practice.

**Comment by simonrepp** [comment]
So, finally getting to respond on this ;) I think it's generally an interesting idea, but also that the notion of whether a faster version is really of use is too dependent on the particular scene, and I would suspect that in 99% of usecases people will just want the final material anyway. (as you already say, unclear if needed in practice)

However, I think your idea contains an alternative path that I do like a lot and want to investigate: Elmyra could render the first iteration of an animation (the initial frames when none exist yet) in a binary-split pattern (assuming an 7 frame animation, the order of rendering would be 4 -> 2+6 -> 1+3+5+7). This way, when Elmyra exports a first video while there are still frames missing, the video could already be full-length and just more sparsely resolved (i.e. it looks stuttery, but it already gives a full impression of the movement and timing of the video). Currently you might get videos that are less than a second long and don't give any impression of the final thing, and as such aren't usable at all, so this would be a cool improvement I think!

**Comment by simonrepp** [comment]
@thesourcerer8: I've added initial support for this in 94075ba594f4cdd0afd7e65ea15d751e6fae456f - for the moment this is now more or less exactly one part of your suggestion (rendering only every n-th frame), just based on an adaptive tree division. :)

The preview vidoes that result from this are already soo much better, so thanks for the suggestion again! I'll see how the counterpart in the exporter performs on the usability level, for the moment the videos are just exported faster (like you suggested) until all frames are there, let's see if the stuttery, length-accurate previews improve it more or the opposite ;) ...
