### ISSUE TITLE
Simplify setup for users

### ISSUE THREAD

**Issue by simonrepp** [apertus-open-source-cinema/elmyra#2]
Currently the setup procedure is ok-ish for developers, but definitely too involved for anyone who just wants to use elmyra. Thus, action needed!

**Python**
- Investigate if the server and renderer can be (adapted to) run with python 2 as well, as a convenience option for OSs that don't offer python 3 by default yet.
- Expand the documentation to cover installing the additionally needed system packages directly from the `requirements.txt` specification.
- Investigate if bundling own python 3 could be a sensible option? (though I'd rather not?)

**Blender**
- **Absolute priority: Do something about the required packages in the blender python environment, biggest show-stopper in the setup procedure.**
- Bundle own blender, readily prepared with the correct python packages?
- Offer packages for python 3.4 and python 3.5 as a zip file to download and manually put into user's blender python environment?
- Offer some kind of configuration option to provide a path to the blender executable?

**ffmpeg**
- Ship it with elmyra releases? (Makes releases platform dependent ...)
- Offer some kind of configuration option to provide a path to the ffmpeg executable?

**Comment by thesourcerer8** [comment]
Hmm, I´ve been thinking about creating Debian packages for elmyra, but I am not sure, whether it´ s worth the effort, if people need it on Windows, OSX, ... as well.
What if we offer a virtual machine, ready to run?
From my point of view, the "how to install blender python plugins" is a problem that needs to be solved better inside Blender itself. I recently failed trying to install zeromq as blender python plugin. (Which I think would be very valuable)
Yes, configuration options for the path to blender and the path to ffmpeg would make it much easier, since you don´ t need to install it systemwide then.

**Comment by andistern** [comment]
Sorry for perhaps not getting the point, but after using Homebrew ( Mac OSX ) to install python3 and pip3 for the needed modules, the "how to install blender python plugins" is just a 

```
for d in Flask-0.10.1.dist-info PIL Pillow-3.0.0.dist-info certifi certifi-2015.11.20.1.dist-info flask natsort natsort-4.0.4.dist-info python_slugify-1.1.4.dist-info slugify
    do cp -R /usr/local/lib/python3.5/site-packages/$d /Applications/blender-2.76-5f0cf67-OSX-10.6-x86_64/blender.app/Contents/Resources/2.76/python/lib/python3.5/site-packages
    echo $d copied
done
```

on the other hand, there is no error in the server or renderer Window, but there is also no output ( perhaps wrong stl files?)

![skeleton-emount-pcbs](https://cloud.githubusercontent.com/assets/1109617/11732405/1d03aa64-9fa4-11e5-9edf-de6334a23de2.jpg)

**Comment by simonrepp** [comment]
@thesourcerer8 As said in the other ticket, I want to bundle as much as possible, this takes care of most things you mentioned. I'm of course happy about contributed packages and/or VM containers, but for the moment I think it's not worth the effort yet, too much is still changing very rapidly or about too.

@andistern Again, bundled blender will remedy the whole installation problem ...

As for the bugreport-ish part, looking into both the server and renderer console usually reveals obvious errors (blender crashing, etc.), some functionality at the moment just might not work as well (not everything's implemented, we're deep in alpha land). Another very viable bug finding strategy is to just open the blender file that elmyra generates, that might show what's going on as well. If you're stuck anyway I'd need more information to say anything about the blank, black output.

**Comment by andistern** [comment]
Hallo Simon,

mit meiner Zeit schauts ähnlich knapp aus wie mit Deiner, was leicht ging ( installieren, Abhängigkeiten auflösen usw.) hab ich probiert, offensichtliche Fehlermeldungen gabs keine, bin schon sehr auf das "Bundle" gespannt! 
Liebe Grüße

A.
Am 21.12.2015 um 14:15 schrieb Simon Repp:

**Comment by simonrepp** [comment]
So now we have multi-platform releases with all the tricky things bundled (621e7a847cc5d892926531352e5dfcea1341d4ec), and only Python 3 remaining as a runtime dependency handled by the system! No further action required on this for a while now, I guess. :)
