### ISSUE TITLE
Specify browser goals/requirements

### ISSUE THREAD

**Issue by simonrepp** [apertus-open-source-cinema/elmyra#3]
Most prominently: Come to a decision whether the flexbox specification (http://caniuse.com/#feat=flexbox) is still too edgy, especially with all the microsoft-related troubles, or if this should be already adopted for future's sake.

**Comment by thesourcerer8** [comment]
I would vote for using flexbox, I don´t think that anyone using elmyra is forced to use older IE´s.

**Comment by simonrepp** [comment]
Considering the tight time constraints to get development done here we'll go with flexbox. (Thanks for the feedback too @thesourcerer8!)

I'll write down some official browser list when I get to it (TM), mobile browsers on small screens will stay nice-to-have for the time being, but tablet and netbooks I'd like to consider in the design process as I can absolutely see them as target users.

**Comment by simonrepp** [comment]
Will know more as soon as the realtime preview is in, although I will try make it gracefully fallback to a reduced featureset if the browser isn't well compatible with WebGL, we'll see how that goes.

**Comment by simonrepp** [comment]
So the flexbox thing was decided, THREE.js theoretically supports anything that handles canvas (and with face-reduced preview models there's theoretically speaking no hardware limitations involved either, so this can actually be closed and handled on demand if we find problems.
