### ISSUE TITLE
add Support for SheepIt Renderfarm

### ISSUE THREAD

**Issue by davidak** [apertus-open-source-cinema/elmyra#39]
by running the Sheep it-Client on your render maschien, you can render your own projects but also distribute the work to others. if you have no active project, a project from other community members get rendered and you earn points. with them you can render more frames on ther people maschines. so the ressources get used more effectively.

https://www.sheepit-renderfarm.com/

**Comment by simonrepp** [comment]
Sounds like a nice-to-have, of which Elmyra certainly has no shortage :), so my question: Do you want to implement that? Or is there some existent practical concern why Elmyra absolutely needs this? Otherwise I'm rather inclined to close this again, because at least for me personally this is right now very far off the roadmap. ;)

**Comment by davidak** [comment]
>Do you want to implement that?

No

>is there some existent practical concern why Elmyra absolutely needs this?

No

>for me personally this is right now very far off the roadmap

Absolutely. It's just a nice-to-have. Maybe you can tag it as such or put it on a "maybe later" milestone.

**Comment by simonrepp** [comment]
My experience is this: If at any time something gets so interesting that you actually want to do it, you won't need a three year old todo item to know it. ;) Until then, this wouldn't-it-be-nice todo item will lie around and steal you 15 seconds of attention and thought every time you're trying to sort through what's actually important in your todo list. But my experience is also this: Everyone should make their own experiences (and it doesn't hurt to put established experiences to the test once in a while), so let's see what happens :)

**Comment by simonrepp** [comment]
With the availability of EEVEE this got further off roadmap territory; elmyra suffers from a "rendering forever" design issue right now and I feel getting back to a deterministic rendering setup would be the better path to take than throwing more computing power at a task that currently not even ever finishes, so with that context and 3 years inactivity I'm closing this, thanks again for bringing it up though!
