### ISSUE TITLE
Updated 2019 release (Blender 2.8 support and stack and dependencies upgrade)

### ISSUE THREAD

**Issue by simonrepp** [apertus-open-source-cinema/elmyra#40]
On the occasion of presenting elmyra at the open hardware month in the fall of 2019 I've decided to put in a few ~~days~~ weeks of work to bring elmyra into mint working condition again. \o/

- [x] Migrate to a more modular, bundling based build process
- [x] Update all frontend/backend dependencies
- [x] Remove blend4web integration (unclear blender 2.8 support, still experimental anyway)
- [x] Upgrade to blender 2.8
- [x] Port server implementation to rust
- [x] Refactor about half of the frontend component implementations
- [x] Make the data directory user-configurable
- [x] Upgrade to blender 2.82
- [x] Add a multitude of command line options for the executable
- [x] Wrap up all obviously loose ends
- [x] Quality assurance: Test and release on all three platforms
  - [x] Linux
    - [x] Possibly improve stdout noise from renderer subprocess alongside blocking windows task
  - [x] macOS
  - [x] Windows
    - [x] Figure out non-blocking subprocess invocation for the renderer process

**Comment by se6astian-pi** [comment]
Hurray!

Let me know if/when you think its time to promote a release or when its ready for wider testing, etc.

**Comment by simonrepp** [comment]
Woohoo thanks, will do! :)

**Comment by simonrepp** [comment]
Phew that was an endeavour, everything always escalates with me :D Linux release is out now, but let's wait till I have built and uploaded the other two platform releases in the coming days before we tell the world haha :)

**Comment by simonrepp** [comment]
All done here. :tada: 

@sp-apertus This can gladly be promoted now as a new release. :) I'm generally available for helping out people who want to actually do something with this and/or develop it further, asides that I'm not going to do any improvements or bugfixes from this point on, as without an actual usecase in the wild it does not really justify the amount of work on this for me right now. (But still I'm glad this is now in a refurbished state and accessible for people to build on it if they wish to do so - that was the intention :)) Hooray!
